In [78]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from statsmodels.formula.api import ols

In [34]:
x_test = pd.read_csv("/Users/yangdongjae/Desktop/2020/대외활동/2020년 공공 빅데이터 청년 인턴십/실무형 프로젝트/roundabout_project/data/X_test.csv")
x_train = pd.read_csv("/Users/yangdongjae/Desktop/2020/대외활동/2020년 공공 빅데이터 청년 인턴십/실무형 프로젝트/roundabout_project/data/X_test.csv")

In [39]:
x_train.set_index('교차로명',inplace = True)
x_test.set_index('교차로명',inplace = True)

In [42]:
y_train = x_train['사고건수']
x_train.drop(columns = ['사고건수'], inplace = True)

KeyError: '사고건수'

In [43]:
y_test = x_test['사고건수']
x_test.drop(columns = ['사고건수'], inplace = True)

In [47]:
min_max = MinMaxScaler()

In [48]:
x_train.columns

Index(['통행량8', '통행량13', '통행량18', '좌회전8', '좌회전13', '좌회전18'], dtype='object')

In [49]:
min_max_tr = min_max.fit_transform(x_train.drop(columns = ['좌회전8', '좌회전13', '좌회전18']))

In [51]:
x = pd.DataFrame(min_max_tr)

In [55]:
x.columns = ['통행량8', '통행량13', '통행량18']

In [56]:
x.columns

Index(['통행량8', '통행량13', '통행량18'], dtype='object')

In [63]:
x.reset_index(drop = True, inplace = True)
x_train.reset_index(drop = True, inplace = True)

In [66]:
x_train

    통행량8  통행량13  통행량18      좌회전8     좌회전13     좌회전18
0   1636   1206   1245  0.198655  0.235489  0.195984
1   5186   3665   5076  0.220401  0.249386  0.244681
2   4786   3301   4340  0.144379  0.168737  0.189401
3   4214   3034   3806  0.166350  0.182268  0.158434
4   3084   2540   2783  0.324903  0.305906  0.253683
..   ...    ...    ...       ...       ...       ...
65  7557   6173   8111  0.066296  0.065446  0.062631
66  3404   2418   3036  0.159518  0.145161  0.131752
67  2532   1920   2209  0.182464  0.044271  0.080127
68  3612   2556   3365  0.289590  0.169405  0.333432
69  4634   3329   4662  0.179543  0.185041  0.197126

[70 rows x 6 columns]

In [69]:
train_x = pd.concat([x, x_train.iloc[:,3:6]], axis = 1)

In [70]:
train_x

        통행량8     통행량13     통행량18      좌회전8     좌회전13     좌회전18
0   0.044092  0.046824  0.000000  0.198655  0.235489  0.195984
1   0.516984  0.518710  0.557967  0.220401  0.249386  0.244681
2   0.463701  0.448858  0.450772  0.144379  0.168737  0.189401
3   0.387505  0.397620  0.372997  0.166350  0.182268  0.158434
4   0.236979  0.302821  0.224002  0.324903  0.305906  0.253683
..       ...       ...       ...       ...       ...       ...
65  0.832823  1.000000  1.000000  0.066296  0.065446  0.062631
66  0.279606  0.279409  0.260851  0.159518  0.145161  0.131752
67  0.163447  0.183842  0.140402  0.182464  0.044271  0.080127
68  0.307313  0.305891  0.308768  0.289590  0.169405  0.333432
69  0.443453  0.454231  0.497670  0.179543  0.185041  0.197126

[70 rows x 6 columns]

In [75]:
train = pd.concat([train_x,y_train.reset_index(drop = True)],axis = 1)

In [82]:
train.head()

       통행량8     통행량13     통행량18      좌회전8     좌회전13     좌회전18  사고건수
0  0.044092  0.046824  0.000000  0.198655  0.235489  0.195984     0
1  0.516984  0.518710  0.557967  0.220401  0.249386  0.244681     3
2  0.463701  0.448858  0.450772  0.144379  0.168737  0.189401    10
3  0.387505  0.397620  0.372997  0.166350  0.182268  0.158434     2
4  0.236979  0.302821  0.224002  0.324903  0.305906  0.253683     1

In [83]:
res = ols('사고건수 ~ 통행량8 + 통행량13 + 통행량18 + 좌회전8 + 좌회전13 + 좌회전18', data = train).fit()

In [84]:
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   사고건수   R-squared:                       0.307
Model:                            OLS   Adj. R-squared:                  0.241
Method:                 Least Squares   F-statistic:                     4.643
Date:                Wed, 12 Aug 2020   Prob (F-statistic):           0.000575
Time:                        11:09:35   Log-Likelihood:                -197.94
No. Observations:                  70   AIC:                             409.9
Df Residuals:                      63   BIC:                             425.6
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4604      1.902      0.242      0.809      -3.340       4.260
통행량8         -15.2132     10.755     -1.415      0.162     -36.704       6.278
통행량13         15.7040      7.190      2.184      0.033       1.335      30.073
통행량18          9.4353     10.979      0.859      0.393     -12.504      31.375
좌회전8          15.5298     15.161      1.024      0.310     -14.768      45.828
좌회전13        -13.1284     19.823     -0.662      0.510     -52.741      26.484
좌회전18          0.7629     15.251      0.050      0.960     -29.714      31.240
==============================================================================
Omnibus:                       13.330   Durbin-Watson:                   2.062
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.705
Skew:                           0.781   Prob(JB):                     0.000143
Kurtosis:                       4.906   Cond. No.                         60.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [85]:
train['통행량'] = train['통행량8'] + train['통행량13'] + train['통행량18']

In [87]:
train

        통행량8     통행량13     통행량18      좌회전8     좌회전13     좌회전18  사고건수       통행량
0   0.044092  0.046824  0.000000  0.198655  0.235489  0.195984     0  0.090916
1   0.516984  0.518710  0.557967  0.220401  0.249386  0.244681     3  1.593661
2   0.463701  0.448858  0.450772  0.144379  0.168737  0.189401    10  1.363331
3   0.387505  0.397620  0.372997  0.166350  0.182268  0.158434     2  1.158123
4   0.236979  0.302821  0.224002  0.324903  0.305906  0.253683     1  0.763802
..       ...       ...       ...       ...       ...       ...   ...       ...
65  0.832823  1.000000  1.000000  0.066296  0.065446  0.062631    18  2.832823
66  0.279606  0.279409  0.260851  0.159518  0.145161  0.131752     7  0.819865
67  0.163447  0.183842  0.140402  0.182464  0.044271  0.080127     4  0.487691
68  0.307313  0.305891  0.308768  0.289590  0.169405  0.333432     3  0.921972
69  0.443453  0.454231  0.497670  0.179543  0.185041  0.197126     6  1.395354

[70 rows x 8 columns]

In [88]:
train.drop(columns = ['통행량8', '통행량13' ,'통행량18'],inplace = True)

In [89]:
train

        좌회전8     좌회전13     좌회전18  사고건수       통행량
0   0.198655  0.235489  0.195984     0  0.090916
1   0.220401  0.249386  0.244681     3  1.593661
2   0.144379  0.168737  0.189401    10  1.363331
3   0.166350  0.182268  0.158434     2  1.158123
4   0.324903  0.305906  0.253683     1  0.763802
..       ...       ...       ...   ...       ...
65  0.066296  0.065446  0.062631    18  2.832823
66  0.159518  0.145161  0.131752     7  0.819865
67  0.182464  0.044271  0.080127     4  0.487691
68  0.289590  0.169405  0.333432     3  0.921972
69  0.179543  0.185041  0.197126     6  1.395354

[70 rows x 5 columns]

In [90]:
res = ols('사고건수 ~ 통행량 + 좌회전8 + 좌회전13 + 좌회전18', data = train).fit()

In [91]:
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   사고건수   R-squared:                       0.255
Model:                            OLS   Adj. R-squared:                  0.209
Method:                 Least Squares   F-statistic:                     5.558
Date:                Wed, 12 Aug 2020   Prob (F-statistic):           0.000654
Time:                        11:13:39   Log-Likelihood:                -200.46
No. Observations:                  70   AIC:                             410.9
Df Residuals:                      65   BIC:                             422.2
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.1361      1.925      0.071      0.944      -3.708       3.980
통행량            3.6555      0.824      4.437      0.000       2.010       5.301
좌회전8          21.2529     15.232      1.395      0.168      -9.166      51.672
좌회전13        -17.5961     20.118     -0.875      0.385     -57.774      22.582
좌회전18          0.3866     15.564      0.025      0.980     -30.698      31.471
==============================================================================
Omnibus:                       16.777   Durbin-Watson:                   2.064
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               28.797
Skew:                           0.840   Prob(JB):                     5.58e-07
Kurtosis:                       5.656   Cond. No.                         79.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""